"""
Functions for generating boutiques descriptors from AFNI help
"""
from pathlib import Path
import re

FINDARGS = re.compile("ARGS=\((.*) ?\)")


def get_complete_args(fname):
    """
    Attempts to find arguments for a given AFNI command

    Parameters
    ----------
    fname : str
        Path to "COMMAND.complete.bash" file generated by running
        `apsearch -update_all_afni_help`

    Returns
    -------
    args : list of str
        Putative arguments for command defined by `fname`
    """
    fpath = Path(fname).expanduser()
    if not fpath.exists():
        raise FileNotFoundError('{} does not seem to exist?'.format(fname))
    args = FINDARGS.findall(fpath.read_text())
    if len(args) < 1:
        raise ValueError('Unable to find arguments for {}'.format(fname))
    args = args[0].strip().replace('\'', '').split(' ')
    return args
